### ISSUE TITLE
Failed to activate the atom-ide-vue package

### ISSUE THREAD

**Issue by navyvet1125** [atom-ide-community/atom-ide-vue#15]
[Enter steps to reproduce:]

1. Just popped up after I started atom

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Debian GNU/Linux
**Thrown From**: [atom-ide-vue](https://github.com/atom-ide-community/atom-ide-vue) package 1.2.0

### Stack Trace

Failed to activate the atom-ide-vue package

```
At Cannot find module 'vscode-languageserver-types'

Error: Cannot find module 'vscode-languageserver-types'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/ide-vue/node_modules/vscode-languageserver-protocol/lib/main.js:37:10)
    at /packages/ide-vue/node_modules/vscode-languageserver-protocol/lib/main.js:44:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/ide-vue/node_modules/atom-languageclient/build/lib/languageclient.js:17:10)
    at /packages/ide-vue/node_modules/atom-languageclient/build/lib/languageclient.js:400:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/ide-vue/node_modules/atom-languageclient/build/lib/convert.js:3:12)
    at /packages/ide-vue/node_modules/atom-languageclient/build/lib/convert.js:204:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/ide-vue/node_modules/atom-languageclient/build/lib/auto-languageclient.js:14:22)
    at /packages/ide-vue/node_modules/atom-languageclient/build/lib/auto-languageclient.js:677:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
```

### Commands

```
     -5:31.8.0 application:open-file (div.tool-panel.tree-view)
     -4:37.1.0 intentions:highlight (input.hidden-input)
     -4:36.8.0 core:copy (input.hidden-input)
     -4:22.2.0 intentions:highlight (input.hidden-input)
     -4:21.8.0 core:paste (input.hidden-input)
     -4:12.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -3:31.8.0 core:save (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-ide-vue 1.2.0 
atom-vue 0.6.0 
atom-vue-router 0.3.0 
busy-signal 2.0.1 
ide-vue 0.1.9 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
vue-fmt 0.1.1 
vue-stylefmt 0.5.0 
```

**Comment by Belar** [comment]
Hello, thanks for the report. 

> popped up after I started atom

Did it happen to an already "functioning" installation or after updating the package? Seems to be an issue with missing dependency, did you try reinstalling the package?
